### ISSUE TITLE
api_key

### ISSUE THREAD

**Issue by 89z** [BackInBash/DeezerAPI#3]
can you advise where you got this key?

https://github.com/BackInBash/DeezerAPI/blob/f20ac257f6d1ade0f1c3c826db566478ea63d29c/DeezerAPI/DeezerAPI/Mobile/Constants.cs#L8

I am writing my own program, and I am wondering how it was acquired

**Comment by BackInBash** [comment]
I got the Key through searching the web as described [here](https://github.com/yne/dzr/wiki#DZR_API)
As for now I haven´t used the mobile api yet so I stick to the WebAPI.

If you really want so grab this mobile key on your own, you should extract it from the Android app https://github.com/dwisiswant0/apkleaks

GL

**Comment by 89z** [comment]
I figured it out. The I mentioned above is from the Deezer iOS `.ipa` file. In regards to how to get that file, it seems that is not easy. I found getting the Android file and key much easier.
